name: sqflite_database_example
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.17.0
  cloud_firestore_platform_interface: ^5.7.7  # Downgrade to resolve compatibility
  cloud_firestore: ^4.9.3
  math_expressions: ^2.0.2
  sqflite: ^2.3.0
  intl: ^0.18.1
  flutter_staggered_grid_view: ^0.7.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
